# Site settings
title: Nicholle Gregor
email: ngregor@albany.edu
description: Nicholle is a student from New York.
url: ngregor.github.io
github_username: ngregor

# Build settings
markdown: kramdown
permalink: pretty
